// try {
//   noExistentFunction();
// }
//
// catch(error) {
//   console.log(error)
// }
//
// try {
//   throw 'myException'
// }
// catch (error) {
//   console.log(error)
// }
